name: MathWhiteboard
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.18
    volumes:
      - /home/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rioLiteop
      - POSTGRES_DB=MathWhiteboard

  redis:
      image: redis:8.0.3
      volumes:
        - redis_data:/data
      restart: unless-stopped

volumes:
  redis_data: