ACCOUNTS_SEND_FRIENDSHIP_REQUEST_SUCCESS = "Заявка отправлена"
ACCOUNTS_SEND_FRIENDSHIP_REQUEST_REJECT = "Нет друга бро"
ACCOUNTS_HANDLE_FRIENDSHIP_REQUEST_NO_PERMISSION = "Ты не ты"

ACCOUNTS_REGISTRATION_CODE_LENGTH = 6
ACCOUNTS_REGISTRATION_CODE_LIFE_SECONDS_IN_CACHE = 60 * 3
ACCOUNTS_REGISTRATION_CODE_REQUEST_EMAIL_KEY_IN_CACHE = "verification_code:{hashed_email}" # Must contain hashed_email